[build]
  command = "npm run build"
  functions = "src/services/"
  publish = "build"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/hello/:splat"